//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terka.FontBuilder.Parser.Output.Positioning
{
    using Terka.FontBuilder.Parser.Output.Context;

    public class ClassContextPositioningTable : ContextRuleTransformationTableBase
    {
        public virtual IGlyphClassDefinition ClassDef
        {
            get;
            set;
        }
    }
}

