//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Terka.FontBuilder.Parser.Output.Positioning
{
    public class PositioningPair
    {
        public virtual ushort SecondGlyphID
        {
            get;
            set;
        }

        public virtual GlyphPositionChange FirstGlyphPositionChange
        {
            get;
            set;
        }

        public virtual GlyphPositionChange SecondGlyphPositionChange
        {
            get;
            set;
        }

    }
}

