//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terka.FontBuilder.Parser.Output.Positioning
{
    public class PositioningClassPair
    {
        public virtual GlyphPositionChange FirstGlyphPositionChange
        {
            get;
            set;
        }

        public virtual GlyphPositionChange SecondGlyphPositionChange
        {
            get;
            set;
        }

    }
}

